### ISSUE TITLE
focus state lost when toggling class to multiple tags

### ISSUE THREAD

**Issue by basaran** [Elv13/tyrannical#86]
To reproduce:

```
tyrannical.tags = {
    {
        name = "1", init = true, exclusive = false, screen = {1,2}, layout = awful.layout.suit.tile.bottom,
        master_width_factor = 0.70,
        class = { "Code", "Xterm" }
    } ,
    {
        name = "2", init = true, exclusive = false, screen = {1,2}, layout = awful.layout.suit.tile.bottom,
        master_width_factor = 0.70,
        class = { "Firefox", "Xterm" }
    } 
}
```

To reproduce:

- Set focus to Code on Tag-1
> go to Tag-2
- Set focus to Firefox on Tag-2
> go to Tag-1
- Focus is no longer on Code, but on Xterm
> go to Tag-2
- Focus is no longer on Firefox, but on Xterm

This only happens when the Xterm default is in place. If you remove the Xterm class from the default settings, and toggle manually using awesomewm, the focus state is kept as expected.

Thank you for Tyrannical, much appreciated.

**Comment by Elv13** [comment]
I will check that once Awesome v4.3 is released and I merge the tyrannical commits related to that. Maybe I am better to fix that in AwesomeWM itself instead of Tyrannical. Right now the other maintainer has no time for Awesome (and I had no time for Awesome last year) so attempting to merge complex new code is a bit stalled.

Awesome v4.3 will merge half of the current Tyrannical code so it wont be necessary anymore and some buggy workarounds can be dropped.
