### ISSUE TITLE
Return from standby results in `nil value (field: 'screen')`

### ISSUE THREAD

**Issue by b0wter** [Elv13/tyrannical#90]
I am using awesome 4.3 with a [copycat theme](https://github.com/troglobit/awesome-copycats). Whenever my laptop returns from standby I get the following error message:

![image](https://user-images.githubusercontent.com/614261/71543521-2ad88700-2974-11ea-94f2-f5af9f9375e9.png)

and the tags are messed up (not in the correct order and the first tag contains all apps despite being exclusive). Restarting awesome fixes the issue.

I am running xubuntu 19.10 and am not sure if tyrannical is the origin of the issue. Any help investigating the problem is appreciated :)

**Comment by Elv13** [comment]
This is probably due to this bug https://github.com/awesomeWM/awesome/issues/1382

It should get fixed in v4.4, but it isn't really completed yet. This was a very, very deep issue and the fix required a large redesign of how screens are handled. Part of the changes are merged, but not *this* part.

Anyway, closing here since this is an upstream issue (and I will fix it there).

I will also merge Tyrannical so it wont be a module anymore. However that might go into 4.5/5.0
